{
  "formatVersion": "1.1",
  "component": {
    "group": "pl.selvin.android",
    "module": "sync-framework",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "pl.selvin.android",
          "module": "auto-content-provider",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sync-framework-1.6.1.aar",
          "url": "sync-framework-1.6.1.aar",
          "size": 30237,
          "sha512": "c93401a80d5fed53dc545b007616ce2e7523780fd9d9aed4f47740cb58877b197073a0fb506f39691635817db5b1fa3bfb7eb09015a4167b6c7fea772f48d3e9",
          "sha256": "4bd9d9176af6717f55c2f8fe548007df689aa9a0208a647f8c6722b24fcb6bfb",
          "sha1": "26852f6aead8ca0c6070774d75f20d7190552aeb",
          "md5": "3e23fede3a1b216d8445c5a1251aac0e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "pl.selvin.android",
          "module": "auto-content-provider",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "sync-framework-1.6.1.aar",
          "url": "sync-framework-1.6.1.aar",
          "size": 30237,
          "sha512": "c93401a80d5fed53dc545b007616ce2e7523780fd9d9aed4f47740cb58877b197073a0fb506f39691635817db5b1fa3bfb7eb09015a4167b6c7fea772f48d3e9",
          "sha256": "4bd9d9176af6717f55c2f8fe548007df689aa9a0208a647f8c6722b24fcb6bfb",
          "sha1": "26852f6aead8ca0c6070774d75f20d7190552aeb",
          "md5": "3e23fede3a1b216d8445c5a1251aac0e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sync-framework-1.6.1-sources.jar",
          "url": "sync-framework-1.6.1-sources.jar",
          "size": 16947,
          "sha512": "0b6fe0c4d73104f8473e5d2df5563ede2e69271035cb6b7966ef63a1e523668f49e588d89482b92bd6b11a1fa5480b7ab5c0a7ceb6a5f2571eeb6bbf7a8f743e",
          "sha256": "44ac3567cf049d7e1c2da337420b776f43f5b37059c655341316a80e10d9bf83",
          "sha1": "38402cce1e359080410c793e74b91b8747e635bf",
          "md5": "6b65fc8d1d7f7506dba9e87d4ddd15e0"
        }
      ]
    }
  ]
}
