{
  "formatVersion": "1.1",
  "component": {
    "group": "pl.selvin.android",
    "module": "auto-content-provider",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "auto-content-provider-3.0.0.aar",
          "url": "auto-content-provider-3.0.0.aar",
          "size": 30180,
          "sha512": "11b2ae3018441116b6a2a2b26d91c9728b86558bdb072c604df5d69f70d49820d130773307736b87fad449897ad84f86ed89d73c973278f50f33993685c22305",
          "sha256": "b8c749738b43f0f875cf8014cc3af8df68a7ae44745996fc48b01b1f556a1b6a",
          "sha1": "6b0affeb6fc9bf5730cba0f455145990431b8fec",
          "md5": "22fd44801fafb0d01071f68fc63b78d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "auto-content-provider-3.0.0.aar",
          "url": "auto-content-provider-3.0.0.aar",
          "size": 30180,
          "sha512": "11b2ae3018441116b6a2a2b26d91c9728b86558bdb072c604df5d69f70d49820d130773307736b87fad449897ad84f86ed89d73c973278f50f33993685c22305",
          "sha256": "b8c749738b43f0f875cf8014cc3af8df68a7ae44745996fc48b01b1f556a1b6a",
          "sha1": "6b0affeb6fc9bf5730cba0f455145990431b8fec",
          "md5": "22fd44801fafb0d01071f68fc63b78d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "auto-content-provider-3.0.0-sources.jar",
          "url": "auto-content-provider-3.0.0-sources.jar",
          "size": 25694,
          "sha512": "f60366a528ecc86fb76ca3da15af47874ecaf6abeba8177947a902569d8ed2c3714fcd50ae624140dd9515d52aa1e0e475e51ffa788c0e1b1fa388eb467d768a",
          "sha256": "014b1116fefd763550d695da240891205eda6d839a226f0d68ddf7194897d1f2",
          "sha1": "7f50fbf86536533469b32fbeeae5b9b2630ecb2c",
          "md5": "5b95824e5f2d5bd89714973c2ad3ba40"
        }
      ]
    }
  ]
}
