{
  "formatVersion": "1.1",
  "component": {
    "group": "pl.selvin.android",
    "module": "sync-framework",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "pl.selvin.android",
          "module": "auto-content-provider",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "sync-framework-4.0.0.aar",
          "url": "sync-framework-4.0.0.aar",
          "size": 49345,
          "sha512": "80ef146df58520c58cd115f1500f253ade2665082161a731d0270a03d0a9cb0025be3f3355bd029c5e4b61794f7d01a2f8db0f6bb1ab05d374f0e65fe8b18957",
          "sha256": "3f01071f2bd3d90fcb8686ba6819defbae8b4cda1f2e6535c7284705095d7868",
          "sha1": "2dec3018b17d8bf094e58be979bbb286c4a5137f",
          "md5": "c097bfc2ef37f69865b77f93f701780d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "pl.selvin.android",
          "module": "auto-content-provider",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "sync-framework-4.0.0.aar",
          "url": "sync-framework-4.0.0.aar",
          "size": 49345,
          "sha512": "80ef146df58520c58cd115f1500f253ade2665082161a731d0270a03d0a9cb0025be3f3355bd029c5e4b61794f7d01a2f8db0f6bb1ab05d374f0e65fe8b18957",
          "sha256": "3f01071f2bd3d90fcb8686ba6819defbae8b4cda1f2e6535c7284705095d7868",
          "sha1": "2dec3018b17d8bf094e58be979bbb286c4a5137f",
          "md5": "c097bfc2ef37f69865b77f93f701780d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sync-framework-4.0.0-sources.jar",
          "url": "sync-framework-4.0.0-sources.jar",
          "size": 32182,
          "sha512": "e6b0789017deff2d0060ade6a94dfca98456b71e8f099f221d9c7b64a2e9fc7d4fe8d24bf2dc22b2900c4f10d24c69fee660459b27f924a0e3cf0fa6d096d17a",
          "sha256": "71d314a8511a489f34aa87af6e8698044a45f534133a859cae9f4aacf38fb8be",
          "sha1": "4399fa64554eb21f2e4305e37bb3a17f998ca3a0",
          "md5": "933080c3da965c89811e5f093e63a43e"
        }
      ]
    }
  ]
}
