{
  "formatVersion": "1.1",
  "component": {
    "group": "pl.selvin.android",
    "module": "auto-content-provider",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "auto-content-provider-4.1.0.aar",
          "url": "auto-content-provider-4.1.0.aar",
          "size": 31737,
          "sha512": "6fa1d5a28a886b278d778536e027addb88108316d4c0df827ff26f5568b34fc080114a904e709a5f651536d3f0066980d98d8473e9650d8d00b10a277fe132e1",
          "sha256": "e4d4e9d2240172de1e5741dd99ed599d08ed5cec7f064d12f6671b13d046bfd3",
          "sha1": "2e2057cab30f87f1af320dbc7fd4f578e0524ad5",
          "md5": "9b2932c2cbf60e50e6fa23f65e26b2c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "auto-content-provider-4.1.0.aar",
          "url": "auto-content-provider-4.1.0.aar",
          "size": 31737,
          "sha512": "6fa1d5a28a886b278d778536e027addb88108316d4c0df827ff26f5568b34fc080114a904e709a5f651536d3f0066980d98d8473e9650d8d00b10a277fe132e1",
          "sha256": "e4d4e9d2240172de1e5741dd99ed599d08ed5cec7f064d12f6671b13d046bfd3",
          "sha1": "2e2057cab30f87f1af320dbc7fd4f578e0524ad5",
          "md5": "9b2932c2cbf60e50e6fa23f65e26b2c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "auto-content-provider-4.1.0-sources.jar",
          "url": "auto-content-provider-4.1.0-sources.jar",
          "size": 25914,
          "sha512": "46b4ba50a50def18869932a46dc230e9bcc840ee6c0b17622efd6b42ad920ce834c155cdb9b894d7f99ae4c81fda3f530c965444d68a43b4f2a548b305e4f0cb",
          "sha256": "e779d5b9ca2c05bd582a4c2325498cf261d06779bc33edcce40943f735e1651a",
          "sha1": "b6b6a9e228b541b783e851497684a96ef7911be8",
          "md5": "cebe5e74d393d93ee9d40625a4a958cd"
        }
      ]
    }
  ]
}
